// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJdEw6HmxMv-GTgAgVu6A6LsXt9ph2dA',
    appId: '1:737959881013:web:494b2a5ea1015ed8a7447c',
    messagingSenderId: '737959881013',
    projectId: 'lesson-5243d',
    authDomain: 'lesson-5243d.firebaseapp.com',
    storageBucket: 'lesson-5243d.firebasestorage.app',
    measurementId: 'G-Q0GB8GSEY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiyvB5mXPZcpFurNs4drqfGqFjLwyweVQ',
    appId: '1:737959881013:android:676980b25e206ac9a7447c',
    messagingSenderId: '737959881013',
    projectId: 'lesson-5243d',
    storageBucket: 'lesson-5243d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaVTt5miLFtsMBUS0DUMRs7W-puJgCyu0',
    appId: '1:737959881013:ios:ab63e47e0d630193a7447c',
    messagingSenderId: '737959881013',
    projectId: 'lesson-5243d',
    storageBucket: 'lesson-5243d.firebasestorage.app',
    iosBundleId: 'com.abdillox.firebaseLesson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaVTt5miLFtsMBUS0DUMRs7W-puJgCyu0',
    appId: '1:737959881013:ios:ab63e47e0d630193a7447c',
    messagingSenderId: '737959881013',
    projectId: 'lesson-5243d',
    storageBucket: 'lesson-5243d.firebasestorage.app',
    iosBundleId: 'com.abdillox.firebaseLesson',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChJdEw6HmxMv-GTgAgVu6A6LsXt9ph2dA',
    appId: '1:737959881013:web:1ef3dc5004aadf0fa7447c',
    messagingSenderId: '737959881013',
    projectId: 'lesson-5243d',
    authDomain: 'lesson-5243d.firebaseapp.com',
    storageBucket: 'lesson-5243d.firebasestorage.app',
    measurementId: 'G-BYD22GD5RK',
  );
}
