name: firebase_lesson
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: any
  cloud_firestore: any
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  just_audio: ^0.9.42
  rxdart: ^0.27.7
  audio_session: ^0.1.21
  flutter_animate: ^4.5.2
  http: ^1.2.2
  rename: ^3.0.2
  rounded_loading_button: ^2.1.0
  provider: ^6.1.2
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  pinput: ^5.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/user_icon.png
    - assets/

